# pyup.io config file
# see https://pyup.io/docs/configuration/ for all available options

branch: main
schedule: ""
update: all
requirements:
  - docs/requirements.txt:
      pin: False
  - /requirements.txt:
      update: insecure
