version: "3.8"

services:
  server:
    build: .
    image: eligibility_server:latest
    ports:
      - 5000
    volumes:
      - ./:/home/calitp/app/
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sleep infinity
    entrypoint: []
    image: eligibility_server:dev
    ports:
      - 5000
    volumes:
      - ./:/home/calitp/app/
