version: "3.8"

services:
  server:
    build: ..
    env_file: .env
    image: eligibility_server:latest
    ports:
      - "5000"
    volumes:
      - ../:/home/calitp/app/
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    entrypoint: []
    env_file: .env
    image: eligibility_server:dev
    ports:
      - "5000"
    volumes:
      - ../:/home/calitp/app/
  docs:
    image: eligibility_server:dev
    entrypoint: mkdocs
    command: serve --dev-addr "0.0.0.0:8000"
    ports:
      - "8000"
    volumes:
      - ../:/home/calitp/app:cached
