trigger:
  branches:
    include:
      - dev
      - test
      - prod
  tags:
    include:
      - 20??.??.?*-rc?*
      - 20??.??.?*
  # only run for changes to Terraform files
  paths:
    include:
      - terraform/*

pr:
  branches:
    include:
      - "*"
  paths:
    include:
      - terraform/*

pool:
  vmImage: ubuntu-latest

variables:
  agency_card: mst-courtesy-cards

stages:
  - template: deploy.yml
    parameters:
      resource_group: $(agency_card)-eligibility-terraform
      storage_account: ${{ replace(variables.agency_card, '-', '') }}tf
