name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - test
      - prod
    tags:
      # pre-release tag
      - "202[3-9].[0-9][0-9].[0-9]+-rc[0-9]+"
      # release tags
      - "202[3-9].[0-9][0-9].[0-9]+"

defaults:
  run:
    shell: bash

concurrency:
  # this expression gives us the name of the deployment environment. It works like a ternary operation (see https://github.com/actions/runner/issues/409#issuecomment-727565588)
  group: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref_name || contains(github.ref, '-rc') && 'test' || 'prod' }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo Testing
    if: startsWith(github.ref, 'refs/tags/')

  deploy:
    needs: test
    # !cancelled() is needed because if the whole workflow was cancelled, we don't want this job to run.
    # (!startsWith(github.ref, 'refs/tags/') || needs.test.result == 'success') is needed because if `test` did run, we only want this to run if `test` succeeded.
    if: (!cancelled() && (!startsWith(github.ref, 'refs/tags/') || needs.test.result == 'success'))
    runs-on: ubuntu-latest
    environment: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref_name || contains(github.ref, '-rc') && 'test' || 'prod' }}

    steps:
      - name: echo names for Docker tags
        run: |
          echo ghcr.io/${{ github.repository }}:${{ !startsWith(github.ref, 'refs/tags/') && github.ref_name || contains(github.ref, '-rc') && 'test' || 'prod' }}
          echo ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          echo ghcr.io/${{ github.repository }}:${{ github.sha }}
