name: Build and publish Docker image

on:
  release:
    types: [ published ]
  push:
    branches:
      - main
    paths:
      - 'data/**'
      - 'eligibility_server/**'
      - 'keys/**'
      - '.github/workflows/docker-publish.yml'
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  build_push_docker:
    name: Package Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push release
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        with:
          push: true
          tags: |
            ghcr.io/${{github.repository}}:${{ github.event.release.tag_name }}
            ghcr.io/${{github.repository}}:latest

      - name: Build and push main
        uses: docker/build-push-action@v2
        if: ${{ github.event_name != 'release' }}
        with:
          push: true
          tags: ghcr.io/${{github.repository}}:main
