name: Run pytests

on:
  pull_request:
    branches: [ "*" ]
    paths:
      - 'data/**'
      - 'eligibility_server/**'
      - 'keys/**'
      - 'tests/**'
      - 'requirements.txt'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          export HASH_TYPE=sha256
          coverage run -m pytest
          coverage report -m
